version: '3.8'

services:
  app:
    build: .
    env_file:
      - .env
    volumes:
      - ./db.sqlite3:/app/db.sqlite3  # Монтирование файла базы данных
      - .:/app
    ports:
      - "8080:8080"
