"""empty message

Revision ID: 7646da09c9be
Revises: 
Create Date: 2025-03-27 22:08:32.809693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7646da09c9be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dateworks', sa.Column('start', sa.Integer(), nullable=False))
    op.add_column('dateworks', sa.Column('end', sa.Integer(), nullable=False))
    op.drop_column('dateworks', 'timework')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dateworks', sa.Column('timework', sa.INTEGER(), nullable=False))
    op.drop_column('dateworks', 'end')
    op.drop_column('dateworks', 'start')
    # ### end Alembic commands ###
